---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorHost
metadata:
  name: emojivoto.preview.mturner.k736.net
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  hostname: emojivoto.preview.mturner.k736.net
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: bounce@datawire.io
  selector:
    matchLabels:
      ambassadorhost: emojivoto.preview.mturner.k736.net
---
apiVersion: x.getambassador.io/v3alpha1
kind:  AmbassadorMapping
metadata:
  name:  emojivoto-mapping
  namespace: emojivoto
  labels:
    ambassadorhost: emojivoto.preview.mturner.k736.net
spec:
  host: emojivoto.preview.mturner.k736.net
  prefix: /test/
  service: web-svc.emojivoto:80
  tls: istio-upstream
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: web
  namespace: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      version: v11
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: web-svc
        version: v11
    spec:
      serviceAccountName: web
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: emoji-svc.emojivoto:8080
        - name: VOTINGSVC_HOST
          value: voting-svc.emojivoto:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: docker.l5d.io/buoyantio/emojivoto-web:v11
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    a8r.io/bugs: https://github.com/datawire/ambassador/issues
    a8r.io/chat: '#ambassador'
    a8r.io/dependencies: emoji-svc.emojivoto, voting-svc.emojivoto
    a8r.io/description: gRPC API for voting and leaderboard
    a8r.io/documentation: https://www.getambassador.io/docs/latest/
    a8r.io/incidents: https://app.datadoghq.com/incidents/introduction
    a8r.io/logs: https://kibana.getambassador.io
    a8r.io/owner: "@cakuros"
    a8r.io/performance: https://linkerd.mturner.k736.net/grafana/d/linkerd-namespace/linkerd-namespace?orgId=1&refresh=1m&var-namespace=emojivoto&var-deployment=web
    a8r.io/repository: https://github.com/a8r-se/sol-eng-preview
    a8r.io/rollouts.deployment: web
    a8r.io/rollouts.image-repo.name: caseykurosawa/emojivoto-web
    a8r.io/rollouts.image-repo.type: dockerhub
    # a8r.io/rollouts.mappings: emojivoto-mapping
    a8r.io/rollouts.scm.branch: main
    a8r.io/rollouts.scm.path: yaml
    a8r.io/runbook: https://www.getambassador.io/docs/latest/topics/running/debugging/
    a8r.io/support: https://support.datawire.io/hc/en-us
    a8r.io/uptime: https://app.datadoghq.com/screen/integration/86/kubernetes---overview?from_ts=162
  name: web-svc
  namespace: emojivoto
spec:
  type: ClusterIP
  selector:
    app: web-svc
  ports:
  - name: http
    port: 80
    targetPort: 8080
